### ISSUE TITLE
AccessMiddleware and OperaLogMiddleware cannot exist at the same time. 

### ISSUE THREAD

**Issue by nipeone** [fastapi-practices/fastapi_best_architecture#234]
If you turn on AccessMiddleware settings, an exception "'async for' requires an object with __aiter__ method, got method" will occur. Besides that, should request.state.ip be set in OperaLogMiddleware? Since OperaLogMiddleware is an optional plugin, if the user disables this plugin, the auth module will throw an exception for missing state.ip because it is used by captcha.

**Comment by wu-clan** [comment]
In fact, OperaLogMiddleware is not optional!

**Comment by nipeone** [comment]
if OperaLogMiddleware is not optional, the PR does not need to handle. but can AccessMiddleware and OperaLogMiddleware exist at the same time?

**Comment by wu-clan** [comment]
I would check out AccessMiddleware, because I hardly ever use it.

**Comment by wu-clan** [comment]
OperaLogMiddleware in order to achieve the function to do some special operations, it seems that with AccessMiddleware (BaseHTTPMiddleware) there are some conflicts, according to the fastapi middleware from top to bottom order of registration, modify the OperaLogMiddleware registration location, make it accessible to more raw data

**Comment by wu-clan** [comment]
OperaLogMiddleware in order to achieve the function to do some special operations, it seems that with AccessMiddleware (BaseHTTPMiddleware) there are some conflicts, according to the fastapi middleware from bottom to top order of registration, modify the OperaLogMiddleware registration location, make it as non-destructive as possible
