### ISSUE TITLE
Nice project and some personal issue.

### ISSUE THREAD

**Issue by linkedlist771** [fastapi-practices/fastapi_best_architecture#315]
Hi, maintainer of this project. I come to know this project using the `ChatGPT` . And I find this project is definitely the best back-end project  using fastapi I ever meet. 

But one `more thing I am not sure is that` there are are so many parts of this project  , what should I start to learn this project? How to glue them together. Kee me updated.😘

**Comment by wu-clan** [comment]
Hello, the project is still in the development stage. Due to many factors, our documentation has not yet started. If you are already familiar with fastapi and have some experience in web framework, I believe you can master it. At the same time, welcome to join our communication group to get more timely feedback.

**Comment by linkedlist771** [comment]
Your code is quite intricate, but I'm managing to understand it bit by bit. The project structure and coding style are really instructive, and I'm looking forward to learning from them. I plan to join the group soon, and I really appreciate your efforts in making this open source. Thanks!
